/**
 * @author Stefano Ceccotti
*/

package simulator.events.impl;

import simulator.core.Agent;
import simulator.events.Event;
import simulator.network.Connection;
import simulator.network.protocols.Header;
import simulator.utils.Time;

/**
 * Class representing an event generated by an agent.
*/
public class AgentEvent extends Event
{
    private Header message;
    private Connection conn;
    
    public AgentEvent( final Time time, final Agent source )
    {
        super( time );
        setSource( source );
        setDestination( source );
    }
    
    public void setMessage( final Header message, final Connection conn )
    {
        this.message = message;
        this.conn = conn;
    }
    
    public Header getMessage() {
        return message;
    }
    
    public Connection getConnection() {
        return conn;
    }
}