/**
 * @author Stefano Ceccotti
*/

package simulator.events.impl;

import simulator.core.Agent;
import simulator.events.Event;
import simulator.events.Packet;
import simulator.utils.SizeUnit;
import simulator.utils.Time;

/**
 * Class representing an event generated by a network protocol.
*/
public class ProtocolEvent extends Event
{
    public ProtocolEvent( Time time, Agent agent, String protocolID )
    {
        super( time, agent );
        _processedByAgent = false;
        _packet = new Packet( 40, SizeUnit.BYTE );
        _packet.addContent( "Protocol_ID", protocolID );
    }
}
